/* SAVE POINT — 스토리 챕터 데이터 (NPC가 순차로 찾아오는 방문자 시스템)
 * 수동 NPC 선택을 폐기하고, 현재 챕터의 npc가 공방에 찾아와 의뢰한다.
 * 각 챕터: story[](도착 대사) → questText(의뢰) → 포션 충족 → doneStory[](감사) → 다음 챕터.
 * wantsQuality 0=평범 / 1=좋음 / 2=완벽. 마지막 챕터 이후 loopMode("freeRequest")로 폴백.
 */
window.CHAPTER_DATA = {
  loopMode: "freeRequest",
  chapters: [
    { id:"ch01", npc:"healer", title:"첫 번째 손님",
      story:[{text:"어서 와요. 드디어 공방을 열었군요, 연금술사.",expr:"default"},{text:"이 여관 1층, 밤에 참 따뜻하죠. 저도 가끔 허브 말리러 들러요.",expr:"relax"},{text:"요즘 잠 못 드는 분들이 늘었어요. 꿈을 잊어버린 것처럼요.",expr:"comfort"},{text:"소문 듣고 왔어요. 솜씨 한 번 믿어봐도 될까요? 🌿",expr:"joy"}],
      questText:"꿈안개 증류액 한 병만요. 품질은 평범해도 괜찮아요, 처음이니까.",
      wantsPotion:"dream_fog_elixir", wantsQuality:0, rewardStardust:20, rewardMaterial:"sleep_deprivation", rewardQty:2,
      doneStory:[{text:"향이 좋네요. 손이 이미 기억하고 있는 것 같아요.",expr:"joy"},{text:"다음에 여관주인 아저씨가 들를 거예요. 채집 얘기 들어봐요. 🌿",expr:"relax"}] },
    { id:"ch02", npc:"innkeeper", title:"여관주인의 부탁",
      story:[{text:"힐러한테 얘기 들었어요. 포션 빚는 사람이 생겼다고.",expr:"default"},{text:"나는 뭐, 말 많이 하는 타입은 아닌데.",expr:"relax"},{text:"손님들이 아침에 일어나도 멍하다는 말을 요즘 자꾸 해요.",expr:"comfort"},{text:"뭐 하나 만들어줄 수 있어요? 🕯️",expr:"default"}],
      questText:"소음 결계 포션 하나요. 좋음 정도면 충분해요.",
      wantsPotion:"silence_seal", wantsQuality:1, rewardStardust:28, rewardMaterial:"notification_overload", rewardQty:2,
      doneStory:[{text:"이거면 되겠네요. 고마워요, 말은 짧게 할게요.",expr:"relax"},{text:"길드마스터가 곧 올 것 같던데. 공식 의뢰래요.",expr:"default"}] },
    { id:"ch03", npc:"guildmaster", title:"공식 의뢰: 길드의 등불",
      story:[{text:"이 공방을 정식 의뢰 대상으로 등록하겠네.",expr:"default"},{text:"길드원들이 요즘 집중을 잘 못 한다는 보고가 들어왔어. 안개가 낀 것처럼.",expr:"cheer"},{text:"품질이 기준을 통과하면 정식 납품 공방으로 올리지. 📜",expr:"default"}],
      questText:"집중 등불 포션, 좋음 이상으로 하나 납품하게.",
      wantsPotion:"focus_lantern", wantsQuality:1, rewardStardust:35, rewardMaterial:"focus_lost", rewardQty:3,
      doneStory:[{text:"합격이야. 길드 장부에 올리지.",expr:"joy"},{text:"참, 라이벌이라는 친구가 자네 얘기 하더군. 📜",expr:"comfort"}] },
    { id:"ch04", npc:"rival", title:"라이벌의 도착",
      story:[{text:"야, 이 공방 생각보다 작네. 근데 냄새는 나쁘지 않아.",expr:"default"},{text:"나 남쪽 마을 출신 연금술사야. 잠깐 머무는 거야.",expr:"relax"},{text:"길드마스터가 여기 칭찬하던데. 솔직히 좀 궁금하더라고.",expr:"joy"},{text:"딱 한 가지만 부탁할게. 😏",expr:"cheer"}],
      questText:"미로 나침반 포션, 완벽으로. 대충 만들면 의미 없잖아.",
      wantsPotion:"maze_compass", wantsQuality:2, rewardStardust:45, rewardMaterial:"decision_paralysis", rewardQty:3,
      doneStory:[{text:"...진짜 완벽이네. 솔직히 좀 놀랐어.",expr:"comfort"},{text:"나중에 마법사 왔으면 재료 얘기 잘 들어. 그 사람 정보 많거든.",expr:"default"}] },
    { id:"ch05", npc:"healer", title:"불안의 그림자",
      story:[{text:"다시 왔어요. 마을에 이상한 기운이 돌아요.",expr:"comfort"},{text:"이유 없는 두려움, 그림자처럼 따라다니는 느낌이요.",expr:"thinking"},{text:"이걸 달래줄 수 있는 건 그림자 방어 포션밖에 없어요. 🌿",expr:"relax"}],
      questText:"그림자 방어 포션, 좋음 이상으로 하나요.",
      wantsPotion:"shadow_ward", wantsQuality:1, rewardStardust:38, rewardMaterial:"anxiety", rewardQty:3,
      doneStory:[{text:"고마워요. 이 마을에 와줘서 정말 잘됐어요.",expr:"joy"},{text:"마법사 선생님이 곧 찾아올 거예요. 🌿",expr:"thinking"}] },
    { id:"ch06", npc:"wizard", title:"마법사의 가설",
      story:[{text:"흥미롭군요. 이 마을의 이상 증상, 오래 관찰해왔습니다.",expr:"thinking"},{text:"수면, 집중, 불안, 결정. 전부 이어져 있어요.",expr:"default"},{text:"막힌 순환을 풀려면 특수 포션이 필요해요. 🔮",expr:"cheer"}],
      questText:"마나 점화 포션, 완벽 품질로.",
      wantsPotion:"mana_kindle", wantsQuality:2, rewardStardust:50, rewardMaterial:"burnout", rewardQty:4,
      doneStory:[{text:"예상보다 더 순수한 포션이군요.",expr:"joy"},{text:"실험 결과가 나오면 다시 올게요. 🔮",expr:"thinking"}] },
    { id:"ch07", npc:"innkeeper", title:"늪에서 건져온 것",
      story:[{text:"채집 다녀왔어요. 공허 연못 깊은 쪽에서 이상한 걸 건졌는데.",expr:"default"},{text:"가라앉아 있던 것들이에요. 슬픔 같은 거, 있잖아요.",expr:"comfort"},{text:"포션으로 건져낼 수 있다면 만들어줄 수 있어요? 🕯️",expr:"default"}],
      questText:"늪 부상 포션, 좋음 이상으로요.",
      wantsPotion:"swamp_float", wantsQuality:1, rewardStardust:40, rewardMaterial:"sadness", rewardQty:3,
      doneStory:[{text:"이 향이면 맞는 것 같아요. 고마워요.",expr:"relax"},{text:"라이벌이 다시 온대요. 이번엔 진지한 얘기 한다고. 🌙",expr:"comfort"}] },
    { id:"ch08", npc:"rival", title:"도망치지 않는 법",
      story:[{text:"나 사실 도망 다니는 거였어. 마을마다 옮겨 다니면서.",expr:"comfort"},{text:"어디서든 완성 못 하는 것들이 쌓이면 그냥 떠났어.",expr:"relax"},{text:"근데 여기 공방 보면서 생각이 달라졌어.",expr:"default"},{text:"마지막으로 하나만 부탁할게. 😏",expr:"thinking"}],
      questText:"차원 잠금 포션, 완벽으로. 한 자리에 있어보려고.",
      wantsPotion:"dimension_lock", wantsQuality:2, rewardStardust:55, rewardMaterial:"escapism", rewardQty:4,
      doneStory:[{text:"...고마워. 진심으로.",expr:"comfort"},{text:"마법사가 뭔가 알아낸 것 같아. 다음 방문 기다려봐.",expr:"joy"}] },
    { id:"ch09", npc:"wizard", title:"순환의 열쇠",
      story:[{text:"실험이 끝났어요. 이 마을의 결정체 순환, 막힌 게 아니었어요.",expr:"thinking"},{text:"당신이 여기서 포션을 빚기 시작한 뒤로 수치가 달라졌어요.",expr:"joy"},{text:"마지막으로 하나만요. 이 순환을 완성하는 포션이에요. 🔮",expr:"cheer"}],
      questText:"오늘의 증류액, 완벽 품질로.",
      wantsPotion:"daily_distillate", wantsQuality:1, rewardStardust:80, rewardMaterial:"decision_paralysis", rewardQty:5,
      doneStory:[{text:"포션이 쌓일수록 이 마을 공기가 달라졌어요. 계속 빚어줄 거죠?",expr:"relax"},{text:"다음엔 더 멀리서 손님이 올지도 모르겠군요.",expr:"thinking"}] }
  ]
};
